### ISSUE TITLE
Change website icon to artifactory logo

### ISSUE THREAD

**Issue by tazard** [Perth-Artifactory/website#14]
Is currently some nextjs default I think:

![image](https://user-images.githubusercontent.com/16077190/107364450-6a314b00-6b16-11eb-83d8-b8671cfc6f8b.png)

Change to artiactory logo. Tidy HQ has this one but might be better with circle centered. 

![image](https://user-images.githubusercontent.com/16077190/107364579-98168f80-6b16-11eb-8317-0b22416e56a9.png)

**Comment by FletcherAU** [comment]
As an alternative, what about the one used on the webcam page?
![webcam favicon](https://user-images.githubusercontent.com/20990280/107367713-977ff800-6b1a-11eb-8008-da30294207d9.png)

**Comment by tazard** [comment]
That one does look pretty good! I should have checked here before rolling out the other one. 

Do you have a source for that? Ill revisit another time.

**Comment by FletcherAU** [comment]
From memory it's just been created from these:
https://space.artifactory.org.au/media/artifactory-logo.png
https://space.artifactory.org.au/media/artifactory-logo.svg

**Comment by tazard** [comment]
That did the trick. Has transparency so works well light and dark mode. Same favicon.ico are other relevant logo files used for webcams, wiki and websites now.
