### ISSUE TITLE
Href style

### ISSUE THREAD

**Issue by FletcherAU** [Perth-Artifactory/website#5]
Right now it's quite difficult to tell when a link is embedded in text, could we change the default href text colour to the yellow used in `text-highlight-1`?

A good example of it in use can be found [here](https://github.com/Perth-Artifactory/website/blob/master/components/_/address.jsx#L28).

**Comment by tazard** [comment]
I second that. Came across it again today when browsing the site.

Any change @vSanjo of a pointer where to look in the CSS?

**Comment by spondy** [comment]
Seems that base styles need to be defined in styles/index.css rather than in tailwind.config.js as has been attempted.
